name: Deploy branch

on:
  push:
    branches:
      - main
      - Task1
      - Task2
      - Task3
      - Task4
      - Task5
      - Task6
      - Task7
      - Task8
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v4

      # Add actual deploy steps here if you need (e.g., upload to a server)
